application: tube-chaser
version: 1
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py

- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /static
  static_dir: static

- url: /media/admin
  static_dir: django/contrib/admin/media

- url: /.*
  script: djangoappengine/main/main.py
